import type { Metadata } from 'next'
import './globals.css'
import { Navbar } from '@/components'


export const metadata: Metadata = {
  title: 'Commerce-API',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        
        </body>
    </html>
  )
}
